### ISSUE TITLE
ValueError: I think I know how to fix it?

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#10]
I got this error:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "***********\lib\lib-tk\Tkinter.py", line 1486, in __call__
        return self.func(*args)
      File "***********\Ways-to-NOT-make-money-master\game.py", line 120, in deduction1
        automoney()
      File "***********\Ways-to-NOT-make-money-master\game.py", line 346, in automoney
        moneymillion = round(float(str(money)[:-7])/10, 1)
    ValueError: could not convert string to float: 

I think  the line `moneymillion = round(float(str(money)[:-7])/10, 1)` should be changed to 

    s=str(money)[:-7]
    moneymillion = round(float(0.0 if s == '' else s)/10, 1)

I changed it, afterwards it went perfectly well with the new code.

**Comment by qlstudio** [comment]
From previous post:
Well, not perfectly well. Saving  the game became quite awkward, since you can't append to a number.

**Comment by DerpfacePython** [comment]
Well, I'm kinda-sorta fixing that in the new update, along with everything else. Right now, it's just about delaying the game-crashing... it'll definitely be fixed.

Thanks!
(qlstudio, you are my saviour)

**Comment by qlstudio** [comment]
(This is TOTALLY off topic)
I don't know why I replaced some letters with "*"

**Comment by qlstudio** [comment]
Now Python is getting [i]wierd[/i]:
You defined moneymillion to be an empty list on line 412;
why does python still throw the error?
(I'm going to look back, because at first it seemed to me the error was twofold)

**Comment by qlstudio** [comment]
I did some testing, but the code didn't crash, saving worked perfectly well now!
(HUH?)

**Comment by qlstudio** [comment]
I made a pull request with the fixed error,
