### ISSUE TITLE
Cheat terminal?

### ISSUE THREAD

**Issue by testitem** [DerpfacePython/Ways-to-NOT-make-money#105]
We could add a special cheat terminal (like the one in the regular cookie clicker) to either test out new features or just give you a boost. What do you think, @joshgit @DerpfacePython ?

**Comment by joshgit** [comment]
No.

**Comment by DerpfacePython** [comment]
I agree with @joshgit (I.e. NO). The game is hackable enough anyway.

**Comment by testitem** [comment]
Yeah.

**Comment by joshgit** [comment]
awww yisssss
