### ISSUE TITLE
GamePy2.py Error! Its because of the python 3 cancerbolaids.

### ISSUE THREAD

**Issue by Cyber-Shadow** [DerpfacePython/Ways-to-NOT-make-money#106]
Hi guys, i received this error when launching the game:

Traceback (most recent call last):
  File "File Path, line 5, in <module>
    import save_and_load
  File "Filepath/save_and_load.py", line 2, in <module>
    from base64 import a85encode, a85decode
ImportError: cannot import name a85encode

Plz no Python3 why the fk do u need a python 3 version. Correct if wrong, wait you cant.

**Comment by joshgit** [comment]
Why can't you run Python3?  Is this 2005?

**Comment by testitem** [comment]
What the hell? This is a reason why Python 3 is better than Python 2.

**Comment by testitem** [comment]
You guys need to understand that ***PYTHON 3.6 IS COMING OUT SUNDAY.*** I see NO REASON to keep using Python two.

**Comment by testitem** [comment]
> Why can't you run Python3? Is this 2005?

I was thinking that too. Can't we get rid of the Python 2 version?

**Comment by DerpfacePython** [comment]
@testitem No. No. No.

**Comment by testitem** [comment]
I know.

**Comment by DerpfacePython** [comment]
Um... I thought about this, and can we make python files that are compatible with both Python 2 and 3 (I.e. one `game.py` that works for both Python 2 and Python 3)?

**Comment by testitem** [comment]
Yeah... like merge those two with "try...except" statements?

**Comment by testitem** [comment]
VERY EASY TO FIX: Change all `a85`s into `b64`s.

**Comment by testitem** [comment]
@Cyber-Shadow , are you happy now???
