### ISSUE TITLE
Too many millions???

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#11]
I was playing it and saved it with $13. After I closed it, I reopened it, but the dollar mark said $13.0m. Why is it so off?
(I did get quite confused with the indexing, thinking how one time the millions are index 25 and later on the millions are index 27.)

**Comment by DerpfacePython** [comment]
Oh... thanks for pointing out that issue. Did not see that coming. Can you post the parts for both cases (i.e. millions in index 25 and 27)?

**Comment by qlstudio** [comment]
Line 618: `money = float(g2[25]) + float(g2[27]) * 1000000` ind 27 is millions
Line 415: `x = ["auto", int(autoclick2), "print", int(printmoney2), "counter", int(counterfeit2), "shares", int(sharecrash2),
         "upg1h1", int(upgcheck1h1), "upg1h2", int(upgcheck1h2), "upg2h1", int(upgcheck2h1), "upg2h2", int(upgcheck2h2),
         "upg3", int(upgcheck3), "upg4",
         int(upgcheck4), "cupg1", int(clickupgcheck1), "cupg2", int(clickupgcheck2), "million", float(moneymillion),
         "money", float(((str(money)[::-1])[:8])[::-1])]` ind 25 is millions

**Comment by qlstudio** [comment]
Fixed in v0.6.2 see pull request #13
