### ISSUE TITLE
Logging in doesn't work.

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#112]
When I try to log in to my account by pressing `Log in`, the login prompt doesn't react - it doesn't not respond, it just doesn't react.

**Comment by testitem** [comment]
Uh... I had this error before. Wait like one or two seconds - it should appear. ( @joshgit created the update-master-every-few-seconds thing to avoid threading)

**Comment by joshgit** [comment]
It still creates accounts, saves, and logs in fine for me.  What did you guys do to the code since then?  How about putting a stack trace in this issue so I don't have to use a crystal ball or augury?

**Comment by DerpfacePython** [comment]
Stack trace?

**Comment by joshgit** [comment]
Any error message?

**Comment by DerpfacePython** [comment]
No error message, which is weird.

**Comment by testitem** [comment]
Line 25: ` if 'debug' in sys.argv:`  
change it into `if True` and see what happens

**Comment by testitem** [comment]
@DerpfacePython @joshgit  is it fixed?

**Comment by testitem** [comment]
it is.
