### ISSUE TITLE
Multiplayer?

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#14]
Should we make the game compatible with more than one player? I'm working on that.

**Comment by Cyber-Shadow** [comment]
What do you mean by this? Being able to have multiple saves / savefiles? Thanks for your feedback.

**Comment by qlstudio** [comment]
Yes, but i was thinking of multiple users stored in one savefile.

**Comment by DerpfacePython** [comment]
(Huzzah! We have labels!)

That could work... but what about portability? To make multiple users in a savefile, we're going to have to figure out a way to do that (which is pretty hard), as well as making the savefile look easy enough to split off your own savefile (if you're saving the game with someone else).

Good idea, though.

**Comment by qlstudio** [comment]
Maybe have one line per person? The savefile is sorted to llllllllloooonnnnnggggg lines of hex-encoded data, so one line of data representing one person may work, but we'd have to add a "username" attribute.
(Talking about attributes, it was surprising you didn't use OOP!)

**Comment by DerpfacePython** [comment]
What is OOP‽ (That's an interrobang.) I know what it stands for (object-oriented programming), but WHAT IS IT?????

**Comment by qlstudio** [comment]
OOP is when define specific data types with certain behaviors to complete something.
For example,

    class Something(object):
        def __init__(self):
            self.i = 121

    something = Something()
    assert isinstance(something, Something) and (something.i == 121)
    
    class Inherited(Something): # inherit all attributes and functions of Something
        def __init__(self, printOut):
            super().__init__(self)
            self.printOut = printOut
        def __str__(self):
            return str(i) + '\n' + str(printOut)
    
    i = Inherited('spam')
    print(i) # should print 121\nspam


OOP is commonly used for Tk graphics, espcially Py3.

    from tkinter import *
    
    class PlainWindow(Frame):
        def __init__(self, master):
            Frame().__init__(self, master)
            self.grid()
    
    t=Tk()
    p=PlainWindow(t)
    p.mainloop()

For single inheritance, use <superclass>.__init__(*args).
For multiple inheritance (REALLY bad idea unless absolutely neccesarry) use super().__init__(args).

Find out more at http://www.tutorialspoint.com/python/python_classes_objects.htm !

**Comment by qlstudio** [comment]
I'm starting to work on an OOP version of the game, but that's delayed since I'm still working on the multiplayer thing....

**Comment by qlstudio** [comment]
Maybe a file for every person will be good enough, and just upgrade that sometime later

**Comment by qlstudio** [comment]
Fixed in 0.6.2 beta

**Comment by DerpfacePython** [comment]
Wait... why is it called "0.6.2 beta"? The last version was 0.6.1 alpha...

**Comment by qlstudio** [comment]
I had to add globals() because a bunch of code is now in the main() function, so the variables are only being used locally. To support the variables for global use, I had to add them into the globals() dictionary.
If I didn't, Python would add them to the locals() dictionary, and the global statement wil fail.

**Comment by DerpfacePython** [comment]
Oh... whoops.
 
It's setting off all sorts of alarms and stuff in PyCharm, so yeah.

**Comment by qlstudio** [comment]
The `globals()` dictionary contains a list of all variables  and functions (etc) the program contains. By adding a key to the `globals()` dict, we assign that variable to the value given, like `globals()[key] = value` is almost exactly same as `key = value`, but in global scope.
