### ISSUE TITLE
Testing new version-IndexError?

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#15]
I got the following IndexError when testing:

    Traceback (most recent call last):
      File "C:\Users\DARREN\Documents\GitHub\Ways-to-NOT-make-money\game.py", line 825, in <module>
        money = float(str(g2[25] + g2[27] + g2[29] + g2[31] + g2[33] + g2[35]))
    IndexError: list index out of range

I thought I had the right savfile!

Use savefile on #13 .

**Comment by DerpfacePython** [comment]
That's odd - it worked perfectly well on my end. I have no idea what the problem is - as far as I know, that's the same savefile I have.

Thanks for reporting the problem!

**Comment by qlstudio** [comment]
Actually, I had the wrong savefile
LOL
