### ISSUE TITLE
Testing new version-OverflowError may be fixed, but it WASN'T

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#16]
The new game version came out! Sadly, when I was testing it, I got this:

    Traceback (most recent call last):
      File "C:\Users\DARREN\Documents\GitHub\Ways-to-NOT-make-money\game.py", line 865, in <module>
        autoclick = int((g2[1] * int(18 * g2[11])) + (g2[1] * int(2 * g2[9])) + g2[1])
    OverflowError: cannot fit 'long' into an index-sized integer

Wasn't overflow error fixed?

**Comment by DerpfacePython** [comment]
Can I see your current savefile?

**Comment by qlstudio** [comment]
`6175746f5f31325f7072696e745f385f636f756e7465725f335f7368617265735f395f7570673168315f315f7570673168325f315f7570673268315f315f7570673268325f315f757067335f315f757067345f305f63757067315f315f63757067325f315f7175696e74696c6c696f6e5f305f7175616472696c6c696f6e5f305f7472696c6c696f6e5f305f62696c6c696f6e5f305f6d696c6c696f6e5f385f6d6f6e65795f3634303533382e38;`

**Comment by DerpfacePython** [comment]
Dammit... I am SUCH an idiot.

I didn't write the line properly, it sees `g2[11]` and `g2[9]` as strings instead of integers.
Thanks for reporting the bug!
