### ISSUE TITLE
"Error" sound?

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#17]
Is it possible to make an error sound by the `bell` function when someone attempts to get an building/upgrade but doesn't have enough money?

(The way to make error sound:

    import Tkinter
    root=Tk()
    root.bell()

)

**Comment by DerpfacePython** [comment]
That could work... I need to put that in the next update.

**Comment by qlstudio** [comment]
Yeah, I would DEFINITELY like to be a collaborator

**Comment by qlstudio** [comment]
By the way, sounds are really cool- check out the documentation for 'winsound'
(I assume you are using Windows)

**Comment by DerpfacePython** [comment]
On the same line of thought, should I insert a `try` and `finally` part for when an error comes up?

**Comment by qlstudio** [comment]
I think so.
What I thought was put a `toplevel.bell()` on line 279 and other lines...

**Comment by qlstudio** [comment]
I added the error sound in v0.6.0-3
