### ISSUE TITLE
0.6.0-2 is VERY buggy

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#18]
I found out many bugs:
1, The money mark said $0.0t. Isn't it supposed to be something like $16.2b?
2, When it said $0.0t, I kept pressing Sharemarket Crash button like something $16 quintillion but the 0.0t did not go down one bit.
3, I restarted it again and it said $0.6m but isn't it supposed to be something like $672,717?
What in the world???

**Comment by qlstudio** [comment]
After I reset the game everything was normal.

**Comment by DerpfacePython** [comment]
So... did it work? Or do I have to fix the bug?

**Comment by qlstudio** [comment]
I don't even know what is causing this error, and  I looked through the whole code!

**Comment by qlstudio** [comment]
It always happens when the money gets around $6.5m. It directly jumps to $0.0t, and there is no way to bring it lower. When I restart the game, I get something like $0.xm.

**Comment by qlstudio** [comment]
Still buggy in 0.6.1a1...???

**Comment by qlstudio** [comment]
More detailed: I currently have $5.0m. Press Counterfeit Companies several times, press Save Game, press +1272 money, money mark turned into $0.0t.

**Comment by qlstudio** [comment]
see #37
