### ISSUE TITLE
Py3 version is OFF TRACK

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#19]
The Python 3 version needs LOTS of editing. I already changed some 20 lines!

**Comment by qlstudio** [comment]
I'm pushing the Py3 version to a different branch called python3, so it won't be confusing

**Comment by DerpfacePython** [comment]
YES! THANK YOU!
Personally I hate Python 3, so...

**Comment by qlstudio** [comment]
Oh. You're welcome.

**Comment by qlstudio** [comment]
By the way, is anyone else helping? The Py3 version needs LOTS of fixing

**Comment by DerpfacePython** [comment]
This isn't really a bug, so I removed the label.

Put it back on if it's needed

**Comment by qlstudio** [comment]
The 2to3 script (Yeah, I'm kinda lazy) didn't work for the hexadecimal enocding, I really need help with the python3 version!!!

**Comment by Cyber-Shadow** [comment]
Hello! We are think to end the Python 3 branch as there is no need for it... Instead we can focus our manpower into Python2 so it can develop faster. If you're worried about different users and what they have on board their computers, there is an .exe version (as you know). Which will work unless they have OSX installed.

**Comment by qlstudio** [comment]
OK. Maybe we can end progress on Python 3 but keep the branch....

**Comment by DerpfacePython** [comment]
(Cyber-Shadow hates Python 3 as well.)
We'll probably keep the Python3 branch, and develop it later when we can.
