### ISSUE TITLE
Bug: 0.6.2 "counterfeit companies" says "auto-clicker"

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#21]
![image1](https://cloud.githubusercontent.com/assets/15697465/12072026/3d975b7a-b09a-11e5-8c6a-e88b65a11228.jpeg)

![image2](https://cloud.githubusercontent.com/assets/15697465/12072030/494b0322-b09a-11e5-8173-23543fd2e917.jpeg)

Counterfeit Companies got subsituted with Auto-Clicker in 0.6.2 beta

P.S. Happy New Year!

**Comment by Cyber-Shadow** [comment]
Thanks for your contributions! It would greatly benefit us if you took screenshots, instead of pictures.

**Comment by DerpfacePython** [comment]
Fixed in V0.6.2!
