### ISSUE TITLE
Global name "upgrades" is not defined in V0.6.2-beta (why are we calling it that?)

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#22]
You can tell from the title.

I press the upgrades button, and it comes up with this:

    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Python27\lib\lib-tk\Tkinter.py", line 1536, in __call__
        return self.func(*args)
      File "C:/Users/hyli/Desktop/New_Locked_Folder/game.py", line 920, in showupgrades
        upgrades.destroy()
    NameError: global name 'upgrades' is not defined

Hope someone (qlstudio, I'm mainly looking at you) can fix this!

**Comment by DerpfacePython** [comment]
Nope, I fixed it... no need to worry.

**Comment by qlstudio** [comment]
Huh? Works on my side
