### ISSUE TITLE
Progress bar? (Also new ideas page)

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#26]
I was wondering if we should make a 'levelling' system and a progress bar for that in the game. Would it be too complex?

Also, if anyone has any ideas, they can post it on this thread.

**Comment by qlstudio** [comment]
Talking about this?

http://www.tkdocs.com/tutorial/morewidgets.html#progressbar

**Comment by DerpfacePython** [comment]
YES! That is exactly what I'm looking for!!!!

**Comment by qlstudio** [comment]
Well, we'd have to determine a  "money goal" like $5q and tell the user how close he/she is to getting there (whoa.... 5q is hours away)

**Comment by DerpfacePython** [comment]
Wait... you can send errors through Python? What...???

**Comment by qlstudio** [comment]
Yeah... 1.0 needs to be something completely different from what we have so far...
By the way, shouldn't we add a Progressbar for the auto-money, like the progressbar shows when you would get your next MPS amount?

API stands for application program interface. I don't really no what it is... how did you get that question? More here: http://www.webopedia.com/TERM/A/API.html

Sending issues is quite easy, you just need the PyGithub extension . See more here: https://github.com/PyGithub/PyGithub

**Comment by DerpfacePython** [comment]
That idea could work... do you mean from Adventure Capitalist?

I got API from the semantic versioning thing, and it says to update to a major version when API can't be backtracked (or something like that, I didn't really understand it either).

**Comment by DerpfacePython** [comment]
My original idea for the progress bar was to make it a levelling system, or something like that.

**Comment by Cyber-Shadow** [comment]
The progress bar is a good idea, i suggest basing it on achievements (Yes we can have achievements) .
I also like the idea of a leveling system.

**Comment by DerpfacePython** [comment]
Continuing on the idea of the progress bar thing, I was thinking we could get two separate levelling systems - a "Clicking" one, and an "Idle" one. We can also have "level-up" upgrades.

"Clicking" levels - simple and efficient, basically it you level up based on how many clicks you do. The "level-up" upgrades would be "Main Button" based.
"Idle" levels - not as simple; you level up based on your lifetime currency (we really need to implement a prestige system). "Level-up" upgrades will be building-based.

So, @qlstudio, @Cyber-Shadow, what do you guys think?

**Comment by DerpfacePython** [comment]
OK everyone - I need ideas for the level-up's... STAT.

**Comment by qlstudio** [comment]
- progressbar telling how close you are to some "money goal" like 5q
- progressbar telling the total click/time ratio
- progressbar telling how much more clicks until a level-up
    - the amount of clicks needed for a click level up should be based by $2^{<Prev level-ups>} \times 25$

@DerpfacePython  @Cyber-Shadow  - RSVP!!!!!!!

**Comment by DerpfacePython** [comment]
LaTeX? What do you need to use LaTeX for?

**Comment by qlstudio** [comment]
We can create a progressbar menu? Like what we did with the upgrades?

**Comment by qlstudio** [comment]
Like we could  create a big button right of Upgrades. When we click it it would reveal a huge chart of progressbars (Or, to make things simple, just place the chart next to the button - eh, it's actually difficult to keep track of how much % should be displayed when the chart is hidden)

**Comment by DerpfacePython** [comment]
Sure, but there's still TOO MANY PROGRESSBARS. We could have a different menu for achievements, but the two main "levelling" systems should be on the main screen.

**Comment by qlstudio** [comment]
My idea was one "clicking" progressbar to show the (money earned from clicks) to (money total earned) ratio. Same thing for "idle". So they'd go forward AND backward?

**Comment by DerpfacePython** [comment]
Maybe... but later on in the game, the "idle" progressbar would always be full, and the "clicking" progress bar would be empty. I was thinking more along the lines of upgrades and stuff.

Also, is there a way to move the images to a separate folder and still get them?

**Comment by qlstudio** [comment]
> Also, is there a way to move the images to a separate folder and still get them?

Of course, just specify the folder like "images/gold.gif"

**Comment by DerpfacePython** [comment]
Oh... because I've drawn some images to go with the individual buildings. Thanks.

**Comment by qlstudio** [comment]
ANY OTHER QUESTIONS??? WHEN ARE WE GOING TO IMPLEMENT THIS???

**Comment by DerpfacePython** [comment]
Uhhhh... we can implement this later... we'll work on the progress bar stuff first.

**Comment by qlstudio** [comment]
That's what I'm talking about!

**Comment by DerpfacePython** [comment]
Oh. We can add this to the `future` branch, it's for V0.8.0.

**Comment by qlstudio** [comment]
Yeah. (It's Sydney time 11:00 PM - you're still awake?)

**Comment by joshgit** [comment]
Is there an IRC channel for this project?  I forget.  If not, please make one on freenode.  I'll lurk in #waystonotmakemoney unless someone else has a better idea.

**Comment by DerpfacePython** [comment]
Maybe we can have a Skype group. Do you people have Skype?

**Comment by joshgit** [comment]
Can I just merge my pull request?  We need take these broken wings and learn to fly again.

**Comment by DerpfacePython** [comment]
Well, sure. It looks pretty good.

**Comment by qlstudio** [comment]
I have Skype, but due to the time zone difference...

**Comment by DerpfacePython** [comment]
Yeah.

**Comment by qlstudio** [comment]
Moved to #86
