### ISSUE TITLE
Specific website for gh-pages?

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#29]
We can add a specific website name to the gh-pages branch so it would be in "normal" format, like "www.google.com". Should we do that, or should we leave it as it is?

**Comment by DerpfacePython** [comment]
Wait... what? That could work, though.
Maybe something like www.waystonotmakemoney.com?

**Comment by qlstudio** [comment]
Yeah... I can definitely do that
