### ISSUE TITLE
Balance says "0.5m"

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#37]
On my screen, it says "Balance: $0.5m". It is not changing, even when I click "+2241 money!". Also, I have 22383 MPS. That means I can get a million onto my balance in ten seconds, however, I think I waited several minutes, it hadn't changed"

**Comment by qlstudio** [comment]
This issue was created by Python, this comment was not

**Comment by DerpfacePython** [comment]
Um... isn't this issue the same as the "0.6.0-2 is VERY BUGGY" one?

**Comment by qlstudio** [comment]
Ooops... however, this still hasn't been fixed
