### ISSUE TITLE
Bug in 0.7 alpha/ 0.7 "beta" (alpha2)

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#40]
I get this when I create an account:

    >>> 
    Yes
    Exception in Tkinter callback
    Traceback (most recent call last):
      File "C:\Python27\lib\lib-tk\Tkinter.py", line 1486, in __call__
        return self.func(*args)
      File "C:\Python27\Ways-to-NOT-make-money-master\game.py", line 87, in createaccount
        gbuildings = (g2[0].decode("hex")).split("_")
      File "C:\Python27\lib\encodings\hex_codec.py", line 42, in hex_decode
        output = binascii.a2b_hex(input)
    TypeError: Odd-length string

    Traceback (most recent call last):
      File "C:\Python27\Ways-to-NOT-make-money-master\game.py", line 1393, in <module>
        if signincheck == signinvalue:
    KeyboardInterrupt
    >>> 

Help!!! (Hey, I think this is another ";" bug)

**Comment by qlstudio** [comment]
Just for debug:

`assert g2[0] == '6175746f5f305f7072696e745f305f636f756e7465725f305f7368617265735f305f7570673168315f305f7570673168325f305f7570673268315f305f7570673268325f305f757067335f305f757067345f305f63757067315f305f63757067325f305f7175696e74696c6c696f6e5f305f7175616472696c6c696f6e5f305f7472696c6c696f6e5f305f62696c6c696f6e5f305f6d696c6c696f6e5f305f6d6f6e65795f302e305f74696d655f305f636c69636b735f30'`

**Comment by qlstudio** [comment]
Through shell debugging, I found it doesn't work in program but does work on shell (????)

    >>> len('6175746f5f305f7072696e745f305f636f756e7465725f305f7368617265735f305f7570673168315f305f7570673168325f305f7570673268315f305f7570673268325f305f757067335f305f757067345f305f63757067315f305f63757067325f305f7175696e74696c6c696f6e5f305f7175616472696c6c696f6e5f305f7472696c6c696f6e5f305f62696c6c696f6e5f305f6d696c6c696f6e5f305f6d6f6e65795f302e305f74696d655f305f636c69636b735f30')
    368
    >>> s = '6175746f5f305f7072696e745f305f636f756e7465725f305f7368617265735f305f7570673168315f305f7570673168325f305f7570673268315f305f7570673268325f305f757067335f305f757067345f305f63757067315f305f63757067325f305f7175696e74696c6c696f6e5f305f7175616472696c6c696f6e5f305f7472696c6c696f6e5f305f62696c6c696f6e5f305f6d696c6c696f6e5f305f6d6f6e65795f302e305f74696d655f305f636c69636b735f30'
    >>> s.decode('hex')
    'auto_0_print_0_counter_0_shares_0_upg1h1_0_upg1h2_0_upg2h1_0_upg2h2_0_upg3_0_upg4_0_cupg1_0_cupg2_0_quintillion_0_quadrillion_0_trillion_0_billion_0_million_0_money_0.0_time_0_clicks_0'
    >>>

**Comment by DerpfacePython** [comment]
Just to add something: I made it this way so I can add a scrollbar in.

As well as that, everything's working perfectly well on my end.

**Comment by DerpfacePython** [comment]
Fixed the bug (I'm pretty sure).

**Comment by qlstudio** [comment]
Debug: in 0.7 alpha 2 "0.7 beta" the error is either in createaccount ln 87 or in <module> ln 1447.
Maybe pdb would help....

**Comment by qlstudio** [comment]
I set a breakpoint on both of the lines, and then it started working well, however the scrollbar....

**Comment by qlstudio** [comment]
Is this fixed or not???
