### ISSUE TITLE
RuntimeError: Calling Tcl from different appartment

### ISSUE THREAD

**Issue by joshgit** [DerpfacePython/Ways-to-NOT-make-money#45]
> python game.py 
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/lib/python2.7/lib-tk/Tkinter.py", line 1073, in mainloop
    self.tk.mainloop(n)
RuntimeError: Calling Tcl from different appartment

**Comment by DerpfacePython** [comment]
Why are you running this in cmd (I'm pretty sure that's cmd)?

**Comment by joshgit** [comment]
No, it's Ubuntu.

**Comment by joshgit** [comment]
How do you expect this to be run, from IDLE?  Or only on a Mac or Linux?

**Comment by DerpfacePython** [comment]
Oh. Whoops.

**Comment by qlstudio** [comment]
this was tested on windows 10 on IDLE (Python 2.7) with PyGithub installed

**Comment by qlstudio** [comment]
What did you ***do*** to make that happen? Press what buttons?

**Comment by qlstudio** [comment]
Wow... I get that error on a Mac too. The error displays before the root screen appears!

**Comment by DerpfacePython** [comment]
Is this still an error?

**Comment by qlstudio** [comment]
Merged to master branch. It's fixed
