### ISSUE TITLE
EXE will not function- there are incorrectly byte-compiled exes

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#50]

**Comment by qlstudio** [comment]
never mind!

**Comment by Cyber-Shadow** [comment]
Hello, DerpfacePython and I started a repository here: https://github.com/Cyber-Shadow/SAAI , I'd like your help to compile an .exe file it, please keep in mind that you will have to include the multiple modules for it to work. Thanks alot.
