### ISSUE TITLE
Code installer-buggy

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#52]
Do NOT install the code on a Python 3.x folder. This is a python 2 program. (I DON'T know why Python 3.x folders are there, either.)

**Comment by qlstudio** [comment]
~~Distutils only supports the current distribution of Python~~ _**Distutils supports ALL INSTALLED PYTHON versions**_

**Comment by DerpfacePython** [comment]
What Python 3.x folders?

**Comment by qlstudio** [comment]
Like you should only install it in your python 2.7 folder. It gives you the option to install in a python 3.x folder (like C:/Python34 on Windows, should be C:/Python27)

**Comment by DerpfacePython** [comment]
So... you're saying we should "push forward" with the Python 3.x version of the game?
