### ISSUE TITLE
Bug report.

### ISSUE THREAD

**Issue by Cyber-Shadow** [DerpfacePython/Ways-to-NOT-make-money#53]
- Reset code is not working!
- Occasional tkinter malformation on game start up.
- Console in background!
- Log out button not working!

**Comment by qlstudio** [comment]
?????????????????????????

**Comment by qlstudio** [comment]
1) Yes
2) ???
3)  There's nothing we could do about that
4) Yes

**Comment by qlstudio** [comment]
When I created the logout button, it worked perfectly well, I'm pretty sure @DerpfacePython messed with the errors and variables which made it not work

**Comment by DerpfacePython** [comment]
I didn't think I did anything in that, it would either be me or @joshgit (who isn't here yet).

**Comment by qlstudio** [comment]
@DerpfacePython  I'm pretty sure you deleted the exception....

**Comment by DerpfacePython** [comment]
What does the exception look like? I don't remember... at all. It could have been me, for all I know, but I need the code itself.

**Comment by qlstudio** [comment]
The `NotSignedIn` exception - something like this:

    class NotSignedIn(Exception):
        pass

**Comment by DerpfacePython** [comment]
That's not me, then. It's @joshgit.

**Comment by qlstudio** [comment]
5139653157f17e069edbeab5b06275fdabb7b6ce  -?

**Comment by DerpfacePython** [comment]
Oh, OK... yeah, that's me. Whoops.

But what did we need that for, anyway? From what I see, it's not needed at all... it's just a random class that doesn't do anything AT ALL. And besides, I fixed it then, so it doesn't really matter... right?

**Comment by qlstudio** [comment]
The installer just creates the code (instead of copy-paste)

**Comment by qlstudio** [comment]
The installer stuff is done (Plus, it installs PyGithub for you!)

**Comment by DerpfacePython** [comment]
Couldn't you do it so that the .bin thing installs the exe version instead of the code? Otherwise, the bin things is kinda redundant (as we already have the code).

**Comment by qlstudio** [comment]
Well, the .exe/.msi has _one_ advantage: It installs PyGithub.

**Comment by DerpfacePython** [comment]
Yeah... and the original version ALSO installs PyGithub... so what's your point, exactly?

**Comment by qlstudio** [comment]
???

**Comment by qlstudio** [comment]
If you copy-paste all the code, unless you had PyGithub installed, you'd have to run `pip install github` or something like that before actually running the code. If you install ZIP, you'd have to extract into your Python folder. So the easiest way is to download the installer executable, and then follow the steps.

**Comment by DerpfacePython** [comment]
But why do we have both installers and the code? One needs to be removed, because it's two things that achieve practically the same purpose.

**Comment by qlstudio** [comment]
wait what? I hadn't decided that yet.... oops

**Comment by qlstudio** [comment]
This thread is obsolete
