### ISSUE TITLE
Add Game Server?

### ISSUE THREAD

**Issue by ghost** [DerpfacePython/Ways-to-NOT-make-money#55]
~~We could take advantage of urllib - we can create a Github Pages website and then read from there. However, it would be difficult to _push_ data - however, we can use the `github` module to change the website HTML. (I'm working on the server now.) Any ideas~~ (USELESS.) Using github3.py?

**Comment by qlstudio** [comment]
I know how to read from the server - however, I don't know how to UPDATE the server. @DerpfacePython  @Cyber-Shadow  @joshgit  Do you have any ideas?

P.S. Here is my URL-reading code:

    import urllib

    def read_from_server():
        website = urllib.urlopen('http://qlstudio.github.io/')
        html_lines = website.readlines()
        html_lines = html_lines[3:-2]
        result = {}
        for i in html_lines:
            line = i[3:-5]
            line = line.split(':')
            result[line[0]] = line[1]
        return result

    print read_from_server()

**Comment by DerpfacePython** [comment]
If we do that, we can get rid of the login stuff, right? You can login from an external server.

**Comment by Cyber-Shadow** [comment]
I am opposed to your ideas as this we intended this to be a single-player game. Also saves are transferable between machines. This is also redundant as there are no multiplayer features currently.

**Comment by qlstudio** [comment]
Never mind, I'm already working on it

**Comment by DerpfacePython** [comment]
But we have no multiplayer features. WE CAN WORK ON IT LATER. We should probably work on something else.

**Comment by DerpfacePython** [comment]
Uh... is this dead?

**Comment by qlstudio** [comment]
Leave this for later, just don't forget it

**Comment by qlstudio** [comment]
OMG this has been delayed SO much. I decided on using github3.py to modify/update the files. And the file server is at https://github.com/qlstudio/WaysToNotMakeMoneyServer

**Comment by josh-valant** [comment]
So what's the goal for the server repo?

**Comment by joshgit** [comment]
What's the plan for this new repo?  Come discuss on IRC.

**Comment by qlstudio** [comment]
It acts as a storage for all the savefiles created by the users. They are accessible from anywhere.

**Comment by DerpfacePython** [comment]
Yeah, but the game is still crappy. There aren't any players, currently (except maybe for us).

**Comment by joshgit** [comment]
We should add other stuff.

**Comment by DerpfacePython** [comment]
So, do you mean we should add other stuff before we move on to this? If anything else, can you further elaborate?

**Comment by joshgit** [comment]
Sorry, I mean adding server-based save files doesn't add much to the game, IMO.  People can take their save files with them if they care about it.  Adding some kind of multiplayer chat or other game features would be a lot cooler.

**Comment by DerpfacePython** [comment]
Yeah, I second that idea, @joshgit. Sure.

**Comment by testitem** [comment]
Is it fixed or not? There hasn't been many replies for a while.
