### ISSUE TITLE
This needs to be talked about.

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#56]
From now on, everybody in this group has to do a pull request before making any changes (me as well). If no one disapproves of the change (or if no one replys within 2 days), it is accepted. If not, then the pull request is scrapped and cancelled. The person disapproving **MUST** have a valid reason for doing so.

**Comment by qlstudio** [comment]
OK.

**Comment by qlstudio** [comment]
(Can the PR be locked so only people in the group can approve/disapprove ?)

**Comment by DerpfacePython** [comment]
Yeah, sure. This is still a WIP, so yeah. I should probably put this in the README as well.

**Comment by qlstudio** [comment]
@Cyber-Shadow  @joshgit  did you notice this

**Comment by qlstudio** [comment]
(not a bug)
