### ISSUE TITLE
Cannot find or remove game when installing using .exe

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#57]
The title is pretty self-explanatory.

**Comment by qlstudio** [comment]
What do you mean? The game exe is in the file "game.exe" (I'm going to update it tomorrow.)

**Comment by DerpfacePython** [comment]
No, like the installers for the Python 2 code.

**Comment by DerpfacePython** [comment]
Side note: What errors were you trying to fetch with the `try` clauses in `signin()`? Just wondering.

**Comment by qlstudio** [comment]
Oh.. the installers might have accidentally installed it in the `Lib/site-packages` location.

Answer  to side note: The program will throw a NameError or something if you close the program without the `try` clause

**Comment by qlstudio** [comment]
Maybe the code would actually be better... the installers happen to be REALLY awkward-behaving.

**Comment by DerpfacePython** [comment]
Yeah.
