### ISSUE TITLE
Type Error??

### ISSUE THREAD

**Issue by alexpimania** [DerpfacePython/Ways-to-NOT-make-money#6]
I am using Python 2.7 and it spits out a type error saying:

Traceback (most recent call last):
  File "/home/pimania/Downloads/Ways-to-NOT-make-money-master/game.py", line 446, in <module>
    g2 = (str(g.read()).decode("hex")).split("_")
  File "/usr/lib/python2.7/encodings/hex_codec.py", line 42, in hex_decode
    output = binascii.a2b_hex(input)
TypeError: Odd-length string

Thanks,

Please help.
It sounds like a cool game!

**Comment by DerpfacePython** [comment]
Unfortunately, the only way to fix this right now is to get rid of the newline inside the savefile (because Github is annoying and saves everything with a newline at the end). I'll try and fix that (and if I can't, I can contact Cyber_Shadow to fix it).

Thanks!

**Comment by Cyber-Shadow** [comment]
There is a temporary solution... Copy this code into savefile.txt:

6175746f5f305f7072696e745f305f636f756e7465725f305f7368617265735f305f7570673168315f305f7570673168325f305f7570673268315f305f7570673268325f305f757067335f305f757067345f305f63757067315f305f63757067325f305f6d6f6e65795f302e30

This should fix your problem...

**Comment by Cyber-Shadow** [comment]
This Issue has

**Comment by Cyber-Shadow** [comment]
This issue has been fixed by DerpfacePython
