### ISSUE TITLE
Two different branches for Python 3?

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#67]
Why are there two separate branches for Python 3 (one for the pictures, one for the code)? We should just put everything into one branch.

Maybe we should just update the whole thing from V0.6.3, and just update the Python 3 branch after a Python 2 branch is updated.

**Comment by qlstudio** [comment]
Sure.

**Comment by qlstudio** [comment]
OK, I used Git Shell to Python3-ize `github`, (sorry for non-pull requesting)

**Comment by qlstudio** [comment]
NOT a good idea. I got rid of Github.

**Comment by qlstudio** [comment]
OK, that's done... I have NO IDEA how to Python3 that chunk of code.

**Comment by DerpfacePython** [comment]
You could just find a Python3 version of `github`, you know.

**Comment by qlstudio** [comment]
There is NONE. Anyways we don't need the reporting thing

**Comment by DerpfacePython** [comment]
Ah... should have done my research. Sorry about that.

**Comment by qlstudio** [comment]
@DerpfacePython Is this dead??

**Comment by DerpfacePython** [comment]
IDK... maybe.

**Comment by qlstudio** [comment]
Done.
