### ISSUE TITLE
Web Browser?

### ISSUE THREAD

**Issue by DerpfacePython** [DerpfacePython/Ways-to-NOT-make-money#74]
Line 127:

`webbrowser.open("https://github.com/DerpfacePython/Ways-to-NOT-make-money/issues/new", new=0, autoraise=True)`

What is this?

**Comment by qlstudio** [comment]
It just opens the issue-reporting Github page, in replace of the fussy autoreport.

**Comment by DerpfacePython** [comment]
It's giving off an error in PyCharm.

**Comment by qlstudio** [comment]
What....? What error?

**Comment by qlstudio** [comment]
PyCharm doesn't support webbrowser or WHAT?

**Comment by DerpfacePython** [comment]
IDK. It just says it's not defined.

I haven't tested the code for the webbrowser to see if it runs, but I'm going to put the issue here for now until I test it.

**Comment by qlstudio** [comment]
Oops... add "import webbrowser"

**Comment by DerpfacePython** [comment]
LOL.

**Comment by qlstudio** [comment]
Yeah, right.
