### ISSUE TITLE
"GameState" class length can be reduced by ~250 lines

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#80]
Method | Equivalent and shorter code
-----------|----------------------
`gamestate.get_autoclick()`| `gamestate.autoclick`
`gamestate.set_autoclick(amount)`|`gamestate.autoclick = amount`
`gamestate.inc_autoclick(amount)`|`gamestate.autoclick += amount`
`gamestate.get_autoclick2()`|`gamestate.autoclick2`
`gamestate.inc_autoclick2(amount=amount)`|`gamestate.autoclick2 += amount`
`gamestate.get_autoprice()`|`gamestate.autoprice`
`gamestate.set_autoprice(amount)`|`gamestate.autoprice = amount`

There are much, much more but I didn't feel like including them.
So could we get rid of the methods?

**Comment by DerpfacePython** [comment]
Probably, yeah.

**Comment by qlstudio** [comment]
What's the point of the class anyways if its just a bunch of getter and setter methods???

**Comment by DerpfacePython** [comment]
LOL, yeah. It takes so long to get rid of the things, though...
