### ISSUE TITLE
Merge Py2 and Py3 into one branch?

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#87]
We could stuff the Py2 version in one folder named `py2` and stuff the Py3 version into another named `py3`...

**Comment by qlstudio** [comment]
I'm gonna do this.

**Comment by qlstudio** [comment]
PLEASE DO NOT ADD COMMITS TO MASTER UNTIL MERGED.

**Comment by qlstudio** [comment]
HELLO?

**Comment by DerpfacePython** [comment]
Wait wait wait... what? I was sick for a while, so I couldn't go on Github. What happened?

**Comment by qlstudio** [comment]
It combines Py2 and Py3 into one branch.
