### ISSUE TITLE
OverflowError

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#9]
I got this error before Tk even started:

    Traceback (most recent call last):
      File "C:\Python27\Ways-to-NOT-make-money-master\game.py", line 530, in <module>
        autoclick = int((g2[1] * int(18 * g2[11])) + (g2[1] * int(2 * g2[9])) + g2[1])
    OverflowError: cannot fit 'long' into an index-sized integer

If you find it helpful, my savefile is here:
`6175746f5f375f7072696e745f375f636f756e7465725f365f7368617265735f32345f7570673168315f315f7570673168325f315f7570673268315f315f7570673268325f315f757067335f315f757067345f315f63757067315f315f63757067325f315f6d6f6e65795f3335373038373330332e31;`

**Comment by DerpfacePython** [comment]
Should be fixed (or delayed for at least 10mins) in V0.6.0... will implement more in further updates (0.6.1, perhaps).
