### ISSUE TITLE
Clicking lotto buy button cause exception

### ISSUE THREAD

**Issue by joshgit** [DerpfacePython/Ways-to-NOT-make-money#92]
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1552, in __call__
    return self.func(*args)
  File "game.py", line 1173, in lotto
    money += lottoprice * 4
TypeError: unsupported operand type(s) for *: 'StringVar' and 'int'

**Comment by DerpfacePython** [comment]
Wait, just a quick question, why did we even have both py2 and py3, @joshgit, @testitem?

**Comment by testitem** [comment]
what? (i think) you told me to create version 3.0.7.1

**Comment by DerpfacePython** [comment]
No I didn't, @testitem, you said you wanted to build a Py3 version.

**Comment by testitem** [comment]
Oh. I built it because that currently both Python 2 and Python 3 are widely used (Python 3.6 is coming out May 15. Today is May 12/13)

**Comment by joshgit** [comment]
We shouldn't need the py2 version.

**Comment by testitem** [comment]
That's insulting to @DerpfacePython

**Comment by joshgit** [comment]
How so?  Most libraries exist for Python 3 now and it's not hard to download and install.

**Comment by testitem** [comment]
I guess so.

**Comment by DerpfacePython** [comment]
@joshgit Well, why shouldn't we keep Py2?

**Comment by testitem** [comment]
Py3 is very similar to Py2 - as well as that, Py3 has some advantages over Py2 (that's just my opinion.)

**Comment by DerpfacePython** [comment]
Yeah, you've got a point there, @testitem. Both Pythons have their advantages and disadvantages.

**Comment by joshgit** [comment]
No, get rid of Py2!

**Comment by testitem** [comment]
We are not getting rid of Py2. (Why? Can't we just merge them into one file using try/except statements??)

**Comment by DerpfacePython** [comment]
Yeah, that works.

**Comment by testitem** [comment]
Fixed (as of [0.8.0a1](https://github.com/DerpfacePython/Ways-to-NOT-make-money/issues/119#issuecomment-226641771) )
