### ISSUE TITLE
Py2 and Py3 diverged.

### ISSUE THREAD

**Issue by qlstudio** [DerpfacePython/Ways-to-NOT-make-money#94]
After @joshgit  merged his pull request into master/py3, we can obviously see Python 2 and Python 3 are headed different directions.

**Comment by joshgit** [comment]
It should be easy enough to make the same changes in the py2 version.

**Comment by qlstudio** [comment]
Yeah, but then Py2 will still be ahead of Py3.

**Comment by qlstudio** [comment]
Fine, do YOU want to do it???

**Comment by qlstudio** [comment]
Never mind, only... @DerpfacePython  0.7.2 got reverted in the process.

**Comment by DerpfacePython** [comment]
Wait what???

**Comment by qlstudio** [comment]
Just re-implement 0.7.2.

**Comment by DerpfacePython** [comment]
What do you mean?

**Comment by joshgit** [comment]
They should be identical with my latest pull request.
