### ISSUE TITLE
ERROR IN GITHUB!!!

### ISSUE THREAD

**Issue by ghost** [DerpfacePython/Ways-to-NOT-make-money#98]
@DerpfacePython Since when have you added "testitem" as a collaborator??? I know testitem is really me in disguise, but what happened was that "he" completely overwritten my commits.

PROOF: Go to "Graphs>Contributions"

**Comment by qlstudio** [comment]
Never mind. Please add @testitem as a collaborator as from now on I am using that account.

**Comment by testitem** [comment]
Hello, this is qlstudio.

**Comment by testitem** [comment]
I deleted my account. That's why I'm testitem now.

**Comment by testitem** [comment]
please add me as collaborator.

**Comment by DerpfacePython** [comment]
Uh... I didn't add him. Someone else added him.

**Comment by testitem** [comment]
thanks for adding me!
