### ISSUE TITLE
ZIP the exe/sfexe?

### ISSUE THREAD

**Issue by testitem** [DerpfacePython/Ways-to-NOT-make-money#99]
The code is right now ***96.4%*** Tcl and only 3.6% Python. We might consider replacing the exe and sfexe folders with a ZIP archive because:

- Github won't recognize the Tcl in the zip archive, so it would be 100% Python
- It takes up less space.

@joshgit  @DerpfacePython  @Cyber-Shadow   What do you think? (Probably only DerpfacePython)

~~Side note: Yay! One issue/pull request to get to #100 !~~

**Comment by DerpfacePython** [comment]
Uh... we have a branch specifically for executable versions.

**Comment by joshgit** [comment]
I think the Tcl stuff is bogus.

**Comment by testitem** [comment]
Oops. I already did it.
